name: checkschool
description: 기숙관리 어플리케이션
publish_to: 'none'
version: 2.1.0+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  firebase_core: ^1.0.4
  firebase_storage: ^8.0.4

  image_picker: ^0.7.4
  adaptive_action_sheet: ^1.0.8

  #Google signup
  sign_in_with_apple: ^3.0.0
  google_sign_in: ^5.0.2
  provider: ^5.0.0

  # decorate
  cupertino_icons:
  google_fonts:
  font_awesome_flutter:

  flutter_local_notifications: ^5.0.0+3

  #Check
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  wifi_info_flutter:
  numberpicker: ^2.1.1

  workmanager: ^0.4.0

  top_snackbar_flutter: ^1.0.0
  modal_bottom_sheet: ^2.0.0

  #setting
  url_launcher: ^6.0.3
  location: ^4.1.1

  #post
  flutter_easyloading: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspe

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SCDream4
      fonts:
        - asset: assets/fonts/SCDream4.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
